### ISSUE TITLE
Convert inspect command to be service provider implementation 

### ISSUE THREAD

**Issue by dspasojevic** [agiledigital/toolform#7]
As a fore-runner to adding more plugins, we want to investigate the limitations of using SPI to define commands to be executed by toolform.

Ultimately, there will be two levels types of plugin:
1 a plugin that adds a new type of command - e.g. inspect; and,
2 a plugin that adds new support to the main 'generate' command.

For this change, the implementation of the service provider will be in the same repo as the interface definition, so it will be automatically published in the same jar. No classpath changes will be required.

In future, we may publish as separate jars.

**Comment by ewheath** [comment]
@dspasojevic For the design of this one, we could plugin-ify everything in the tool, but to me it seems more like we just want to have plugins for `generate` itself.  If generate is a https://github.com/scopt/scopt#commands kind of option then we could run `toolform generate jenkins2-pipeline` or `toolform generate favourite-other-thing` and have the plugin framework only extend that command.

Maybe there is another use case I am missing?

If we want arbitrary command line args extension, they I would either need to bleed scopt into the plugin interface or cook up a pretty generic descriptor of a command line option definition.
